// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--ExyJa0fqFc7FghX97At_AJ7CyWT4EE',
    appId: '1:1052447962559:web:0a2823de2052292ed65d0a',
    messagingSenderId: '1052447962559',
    projectId: 'flutter-test-abcb1',
    authDomain: 'flutter-test-abcb1.firebaseapp.com',
    storageBucket: 'flutter-test-abcb1.appspot.com',
    measurementId: 'G-9JYV9Q8Y21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4h3k4isHu7BAKNHVClk7XGEBfdT82aN8',
    appId: '1:1052447962559:android:e96a2a5811c4dd7ad65d0a',
    messagingSenderId: '1052447962559',
    projectId: 'flutter-test-abcb1',
    storageBucket: 'flutter-test-abcb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKO6cej-jabCKfNk4UHGu3QtvqT1T-VpI',
    appId: '1:1052447962559:ios:a672dff41e1844a8d65d0a',
    messagingSenderId: '1052447962559',
    projectId: 'flutter-test-abcb1',
    storageBucket: 'flutter-test-abcb1.appspot.com',
    iosClientId: '1052447962559-if568kfh7rp58ukab87c8231cvmjstrs.apps.googleusercontent.com',
    iosBundleId: 'com.goswapp.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKO6cej-jabCKfNk4UHGu3QtvqT1T-VpI',
    appId: '1:1052447962559:ios:a672dff41e1844a8d65d0a',
    messagingSenderId: '1052447962559',
    projectId: 'flutter-test-abcb1',
    storageBucket: 'flutter-test-abcb1.appspot.com',
    iosClientId: '1052447962559-if568kfh7rp58ukab87c8231cvmjstrs.apps.googleusercontent.com',
    iosBundleId: 'com.goswapp.crudFirebase',
  );
}
